### ISSUE TITLE
uninitialized constant AutoIncrement::ActiveRecord::Base in Rails 4.1

### ISSUE THREAD

**Issue by taelton** [felipediesel/auto_increment#4]
I am using Rails 4.1 and Ruby 2.1.1, and get this error message in every page in my application after installing the gem.  When I uninstall the gem, everything works again.

uninitialized constant AutoIncrement::ActiveRecord::Base

Trace:
```
activerecord (4.1.0) lib/active_record/schema_migration.rb:10:in `table_name'
activerecord (4.1.0) lib/active_record/migration.rb:826:in `schema_migrations_table_name'
activerecord (4.1.0) lib/active_record/migration.rb:834:in `current_version'
activerecord (4.1.0) lib/active_record/migration.rb:843:in `needs_migration?'
activerecord (4.1.0) lib/active_record/migration.rb:389:in `check_pending!'
activerecord (4.1.0) lib/active_record/migration.rb:377:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.0) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.0) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.0) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.0) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/static.rb:64:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.1.0) lib/rails/engine.rb:514:in `call'
railties (4.1.0) lib/rails/application.rb:144:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
/home/action/.parts/packages/ruby2.1/2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/home/action/.parts/packages/ruby2.1/2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/home/action/.parts/packages/ruby2.1/2.1.1/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by felipediesel** [comment]
Hi,

Probably related to Rails version, I'll take a look at this issue.

**Comment by felipediesel** [comment]
@taelton Have you tried it in a brand new app? I cannot reproduce the error.

**Comment by felipediesel** [comment]
@taelton I just published a correction.

**Comment by taelton** [comment]
Awesome, thanks. I'm sorry that I wasn't responsive to your request to try it in a new app.  Work got busy. 😊 I appreciate you chasing down the issue.

Tim

-----Original Message-----
