### ISSUE TITLE
Arbitrary migrations raise NameError

### ISSUE THREAD

**Issue by kyledcline** [felipediesel/auto_increment#5]
After bundling auto_increment and calling it as a class method in a model, any further arbitrary (and unrelated) database migrations raise `NameError: uninitialized constant AutoIncrement::ActiveRecord::Base`. This makes the entire gem unusable.

Ruby 2.2.0
Rails 4.2.0
auto_increment 1.1.0

`rake db:migrate --trace` output:

```
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
rake aborted!
NameError: uninitialized constant AutoIncrement::ActiveRecord::Base
/Users/kylecline/ticket_win/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/schema_migration.rb:13:in `table_name'
/Users/kylecline/ticket_win/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/schema_migration.rb:21:in `table_exists?'
/Users/kylecline/ticket_win/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/schema_migration.rb:25:in `create_table'
/Users/kylecline/ticket_win/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:781:in `initialize_schema_migrations_table'
/Users/kylecline/ticket_win/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:922:in `initialize'
/Users/kylecline/ticket_win/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `new'
/Users/kylecline/ticket_win/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/Users/kylecline/ticket_win/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/Users/kylecline/ticket_win/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/kylecline/ticket_win/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/kylecline/.rvm/rubies/ruby-2.2.0/bin/rake:33:in `<main>'
```

**Comment by felipediesel** [comment]
@kyledcline I just published a correction.

**Comment by kyledcline** [comment]
@felipediesel Thanks!
